#!/bin/bash

word1=id
word2=next
word3=manager

echo "Generated words:"
echo "com     -> $word1"
echo "rifsxd  -> $word2"
echo "ksunext -> $word3"
echo ""

# Export variables for use in find -exec
export word1 word2 word3

# Rename directories
find . -depth -type d -name 'com' -execdir mv {} "$word1" \;
find . -depth -type d -name 'rifsxd' -execdir mv {} "$word2" \;
find . -depth -type d -name 'ksunext' -execdir mv {} "$word3" \;

# Replace inside files
find . -type f -exec sed -i \
    -e "s/com\.rifsxd\.ksunext/$word1.$word2.$word3/g" \
    -e "s/com\/rifsxd\/ksunext/$word1\/$word2\/$word3/g" \
    -e "s/com_rifsxd_ksunext/${word1}_${word2}_${word3}/g" {} +

# Append '-spoofed' to managerVersionName in build.gradle.kts
# Skip versionName spoofing - using hard-coded version 33200 (v3.3.0)

if [ -f "./app/build.gradle.kts" ]; then
    sed -i '/val managerVersionName:/a val managerVersionNameSpoofed = "${managerVersionName}-enjoy"' ./app/build.gradle.kts
    sed -i 's/outputFileName = "KernelSU_Next_${managerVersionName}_${managerVersionCode}-\$name.apk"/outputFileName = "Next_Manager_${managerVersionNameSpoofed}_${managerVersionCode}-\$name.apk"/' ./app/build.gradle.kts
fi

echo "Done."
